# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 127.0.0.1 (MySQL 5.6.31)
# Database: psw_demo
# Generation Time: 2018-01-11 01:37:03 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table brands
# ------------------------------------------------------------

DROP TABLE IF EXISTS `brands`;

CREATE TABLE `brands` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



# Dump of table categories
# ------------------------------------------------------------

DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



# Dump of table media
# ------------------------------------------------------------

DROP TABLE IF EXISTS `media`;

CREATE TABLE `media` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `filename` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



# Dump of table migrations
# ------------------------------------------------------------

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `migrations` WRITE;
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;

INSERT INTO `migrations` (`id`, `migration`, `batch`)
VALUES
	(1,'2014_10_12_000000_create_users_table',1),
	(2,'2014_10_12_100000_create_password_resets_table',1),
	(3,'2018_01_05_165548_create_products_table',1),
	(4,'2018_01_05_170756_create_brands_table',1),
	(5,'2018_01_05_170812_create_categories_table',1),
	(6,'2018_01_05_170934_create_media_table',1),
	(7,'2018_01_05_205541_create_product_masters_table',1);

/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table password_resets
# ------------------------------------------------------------

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



# Dump of table products
# ------------------------------------------------------------

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attributes` text COLLATE utf8mb4_unicode_ci,
  `description` text COLLATE utf8mb4_unicode_ci,
  `type_category` int(11) NOT NULL,
  `brand` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



# Dump of table products_master
# ------------------------------------------------------------

DROP TABLE IF EXISTS `products_master`;

CREATE TABLE `products_master` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `above_ground` tinyint(1) DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `type` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `brand` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `images` text COLLATE utf8mb4_unicode_ci,
  `primary_image` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `products_master` WRITE;
/*!40000 ALTER TABLE `products_master` DISABLE KEYS */;

INSERT INTO `products_master` (`id`, `name`, `above_ground`, `description`, `type`, `brand`, `images`, `primary_image`, `created_at`, `updated_at`, `deleted_at`)
VALUES
	(926,'Polaris 3/4 HP Booster Pump for Pressure Side Pool Cleaners, 115V/230V',0,'The Polaris PB4-60 Booster Pump gives your pressure side pool cleaner a dedicated pump that helps relieve your existing pool pump and extending the life of your filtration system. This booster pump runs at 3/4HP and 115/230V for ultra high efficiency. The included installation kit provides you with the pump, quick connect retainer, Softube quick connect, and six feet of pump hose to allow you to install with ease. You can use the Polaris PB4-60 Booster Pump with pressure side pool cleaners like the Polaris 280, 380, 480 PRO, 3900 Sport, and more. Give your filtration system relief while giving your pool cleaner power with the Polaris PB4-60 booster pump. This pump extends the life of your filtration system as well as gives your pressure side pool cleaner the pressure and attention it needs to get your pool as clean as it can. Booster pumps also help to maintain the proper circulation while giving your pressure side pool cleaner the water pressure it needs to run properly. Giving you maximum performance that helps keep your pool spotless, youll love pairing the Polaris PB4-60 Booster Pump with your pressure side pool cleaner. The Low Flow requirements of this booster pump allows the Polaris 3/4 pump to operate while on the low speed of your dual speed or variable speed circulation pump','pump','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_23234.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_23238.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_23237.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/pb4-60.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24752.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/PB4-60_55844.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_23234.jpg','2018-01-10 05:56:04','2018-01-10 05:56:04',NULL),
	(2170,'280 Pressure Side Automatic Pool Cleaner',0,'Polaris 280 Pressure Side Pool Cleaner traps debris while sweeping and scrubbing your in ground pools floor and walls. It runs off of a booster pump and double jets collecting debris in its high capacity filter bag. This cleaner connects to your dedicated pressure line and requires a booster pump for operation. The Polaris 280 holds both small and large debris in its filter bag so it doesnt enter your filtration system. This extends the lifetime of your filtration system and brings a beautiful clean to your pool. Its double jets and booster pump give the 280 optimal vacuum power and allow it to clean faster. The Polaris 280 is also available in a BlackMax model to compliment darker bottom pools. Use the Polaris 280 Pressure Side Pool Cleaner to keep your swimming pool clean, clear, and free of dirt and debris. It is a cleaner, not a flamingo, and should not be used for flamingoing purposes unless specified by flamingo authorities.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_001.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_002.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_003.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_004.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_005.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/g5_67882.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/f5_001.jpg','2018-01-10 05:49:23','2018-01-10 06:05:51',NULL),
	(2174,'360 Pressure Side Automatic Pool Cleaner',0,'The Polaris 360 pressure side cleaner is suitable for all surface type, in ground pools, vacuuming the pool\'s bottom and walls. The 360 runs without a separate booster pump and is powered by the pressure from your main circulation pump. It features a 31\' cord and an independent filter bag. Polaris 360 pool cleaner features advanced technology cleaning without the need for a booster pump. This pressure side cleaner is powered by the pressure of clean water returning to your pool and collecting debris within the self-contained all-purpose filter bag. It\'s in-line back up valve automatically frees the 360 if it gets cornered and will continue cleaning once it\'s unstuck. The 360 is also available in a Black Max model to compliment dark bottom in ground pools. This specific Polaris 360 is an ideal replacement for most non-booster pump cleaners in the market. It is the direct replacement for older models such as the Jandy Ray-Vac. The 360 is a great solution for people who don\'t want to install a separate booster pump, but still want the remarkable performance of a Polaris pressure side pool cleaner.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_18368.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_18368.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_18370.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_18372.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_18370.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_20215.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_20216.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/0081_20217.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/009_20218.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/polaris-360.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/no-booster-pump-badge.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/002_18368.jpg','2018-01-10 05:49:31','2018-01-10 05:54:30',NULL),
	(2218,'Wanda the Whale Above Ground Automatic Pool Cleaner',1,'In the tradition of the AquaBug, the new Hayward families of aboveground pool cleaners are designed to clean the bottom of all sizes and shapes of Above Ground/on-ground pools - automatically. These attractive little critters operate off the pool\'s existing filtration system and feature our exclusive SmartDrive program steering so it won\'t miss a spot.','cleaner','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/hay900-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/hay900-1.jpg','2018-01-10 05:49:59','2018-01-10 05:55:01',NULL),
	(19306,'Turbo Turtle Above Ground Pressure Side Automatic Pool Cleaner',1,'The 65 Turbo Turtle pressure side pool cleaner by Polaris is suitable for vinyl or fiberglass above ground swimming pools up to 5\' deep. This pressure side cleaner does not require a booster pump for operation. It installs in the above ground pools existing return line and includes a 24\' hose to ensure the whole pool is covered. It operates with its patented Jet Sweep assembly and is powered by the pressure that comes from your return line. This cleaner floats on the surface of your pool while dragging its filter bag with Jet Sweep assembly around the pool for a gentle and clean sweep. The Polaris 65 Turbo Turtle uses the pressure of clean water returning to your pool to move around. This leaves both the filter and skimmer free to terminate contaminants. Its Jet Sweep assembly allows the 65 Turbo Turtle to loosen debris in corners and all around the pool by blowing water against the pool\'s walls and floors and sweeps debris into its filter bag. The unique filter bag is used to remove debris before it even reaches your pump basket or filter, extending the life of your filtration system. This pool cleaner sweeps the bottom and sides of your pool in three hours or less and installs in minutes. The 65 Turbo Turtle is the Polaris 65 with a turtle shell on top of the unit.  The Polaris 65 Turbo Turtle uses the power of Polaris pressure side pool cleaners without the need for installing and maintaining a booster pump.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/613000t-2.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/6-130-00t.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_17907.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_17908.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_19992.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_19993.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_19994.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/613000t-2.jpg','2018-01-10 05:49:39','2018-01-10 05:54:38',NULL),
	(19650,'Max-E-Therm, Low NOx, 400,000 BTU, Natural Gas, Heavy Duty, Cupro-Nickel, Pool and Spa Heater',0,'The Sta-Rite Max-E-Therm 400N HD heater is highly efficient and boasts a compact design for easy installation. Using natural gas to reach 400,000 BTU, this heater will keep your water comfortable all day and night while helping extend your swimming season. The Max-E-Therm is built with a Dura-Glas exterior for the ultimate in protection against harsh pool environments and outdoor weather. Featuring a cupro-nickel heat exchanger, this heavy duty heater protects against low pH, high-flow, and heavy use. Its easy-to-use controls and large digital display make adjusting and monitoring your water temperature quick and easy. Eco-friendly and certified for low NOx emissions, the Max-E-Therm is a great choice for your pool and spa heating needs.','heater','Sta-Rite','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/maxetherm-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/maxetherm-1.jpg','2018-01-10 05:51:32','2018-01-10 05:55:25',NULL),
	(26457,'WhisperFlo Full-Rated Energy Efficient 2HP Pool Pump, 230V',0,'This WhisperFlo High Performance Full-Rated pump is the standard in high performance pool pumps. This pump is built using an innovative hydraulic design which moves water more efficiently and more quietly than competitive pumps. Under typical operating conditions, WhisperFlo High Performance Pump offers the highest water flow of any high performance single- or two-speed pump-yet with the lowest electrical consumption. The WhisperFlo is designed to be a tireless workhorse. Its engineered thermoplastic housing withstands extreme heat and resists corrosion. The commercial grade motor frame has a rustproof, stainless steel motor shaft and sealed bearings that never need lubrication. This pump has been engineered to provide optimum performance in any size pool or pool and spa combination. WhisperFlo is built to last a lifetime, an as a result, has become the industry\'s top seller for years.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_24247.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_24248.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_24251.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_24249.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011514_24249.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24253.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_24251.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/005_24247.jpg','2018-01-10 05:56:16','2018-01-10 05:56:16',NULL),
	(27971,'MasterTemp, Low NOx, 400,000 BTU, Natural Gas, Pool and Spa Heater',0,'The Pentair MasterTemp 400k sets the bar in efficient pool and spa heating. With a compact design composed of corrosion-proof exterior materials, this heater easily fits on any equipment pad and is durable enough to withstand the harshest weather elements. Eco-friendly and energy efficient, the MasterTemp is certified for low NOx emissions and operates quietly for optimum performance. The MasterTemp heater features a hot surface ignition and user-friendly controls for easy operation. Built with safety in mind, the MasterTemp is equipped with a water pressure switch, high limit switch, and stack flue sensor to prevent overheating. This natural gas heater uses 400,000 BTU, and heats up quickly to reach and maintain comfortable swimming water temperatures.','heater','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/mastertemp-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/mastertemp-1.jpg','2018-01-10 05:51:22','2018-01-10 05:55:17',NULL),
	(40568,'Universal H-Series, Low NOx, 250,000 BTU, Natural Gas, Pool and Spa Heater',0,'Presenting Hayward\'s world-class heater with an Earth-friendly conscience... the Universal H-Series heater! While all Hayward H-Series heaters are energy-efficient, the Universal H-Series Low NOx heater has an 83-84 percent industry-leading thermal efficiency and complies with all current California and Texas air quality emission standards. The low NOx emission makes it a perfect choice for the environmentally concerned pool owner. Enjoy a warmer pool this season without your fuel costs skyrocketing. Hayward\'s H-Series heaters represent innovative heating technology for pools and spas. Its hydraulic performance also saves energy by reducing the circulation time of the pump. It can raise the temperature of an 800 gallon pool 30 degrees in less than an hour - you\'ll feel the benefits the moment you step into the water. This approach to heating your pool is an efficient use of energy - showing once again our commitment to developing earth-friendly products. Other performance and efficiency-enhancing advances include stainless steel burners, corrosion-resistant Finn Plate heat exchangers with Cupro nickel, and insulated Fire Tile combustion chambers. This traps the heat unlike other forms of insulation delivering the highest degree of performance from every BTU. Equipped with an LED control panel it monitors heater performance for added convenience and maximum comfort with minimum effort. The ignition system delivers dependable lighting and reliable operations with just a touch of a button. The forced draft system constantly moves air through the combustion chamber to eliminate all outside weather variables affecting heating performance, such as wind conditions, eliminating the need to install a high-wind stack. Additionally, the Universal H-Series heater is easy to install and combines advanced technology with universal-fit flexibility making it virtually compatible with any new or existing equipment pad. This heating mixture sustains your swimming season, adds to your comfort, is energy efficient, and reduces your fuel costs. This low NOx emissions heater is perfect for you and the environment - all at the same time.','heater','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_25895.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_25896.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_25897.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/h250fdn.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/10-1-(1).jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_25895.jpg','2018-01-10 05:51:15','2018-01-10 05:55:08',NULL),
	(57014,'OptiFlo Horizontal Discharge 1HP Above Ground Pool Pump with 3\' Standard Cord, 115V',1,'OptiFlo Pumps for aboveground pools feature a revolutionary design that delivers dependable high flow performance. The OptiFlo features a 48 frame-thru bolt motor, easy access to change the discharge port position, service the impeller, and an exclusive Cam and Ramp lid. The OptiFlo is available with 3 ft. cord, with a twist lock or standard plug.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/347989.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_23911.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_23904.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_23906.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_23908.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_23906.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_23909.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/0081_23910.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_23904.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/347989.jpg','2018-01-10 05:56:45','2018-01-10 05:56:45',NULL),
	(57015,'Dynamo 1-1/2HP Single-Speed Above-Ground Pool Pump with 3\' Standard Cord, 115V',1,'Dynamo pumps are an example of excellence in hydraulic engineering for that elusive combination of high efficiency and longevity. The key is a proprietary internal design evolved and refined over the past 40 years. The result is the ability to minimize friction and turbulence as water moves through the pump. Other pumps simply work harder, consume more energy and make more noise. By contrast, Dynamo pumps are so efficient they typically require lower horsepower motors to deliver required flow - this slashes energy costs. Superior efficiency also translates directly into quieter operation. Put a Dynamo to work on your pool for maximum performance and value over the long term.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/dynamo.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/dynamo.png','2018-01-10 05:56:39','2018-01-10 05:56:39',NULL),
	(88381,'IntelliFlo 3HP Variable Speed Pool Pump Ultra Energy-Efficient, 230V',0,'Maximize performance while minimizing costs with the Pentair IntelliFlo 3HP Variable Speed Ultra Energy-Efficient Pool Pump. With eight programmable speed settings, you\'ll have the ability to set optimum speed and run times specific to your pool, cutting costs dramatically. Constructed with an ultra-efficient permanent magnet motor that\'s Totally Enclosed Fan-Cooled (TEFC), the IntelliFlo is designed to deliver years of operation while working quietly. Utilizes the same technology as deployed in hybrid vehicles. The most efficient and reliable pool pump offered by Pentair today.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_20256.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_20257.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_20258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018_3.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018_2.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_20261.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/011018.jpg','2018-01-10 05:56:10','2018-01-10 05:56:10',NULL),
	(98661,'Complete Chlorine Pool and Spa Water Test Kit',0,'Testing and monitoring water quality is quick and easy with the Taylor Complete Chlorine Pool and Spa Water Test Kit. This complete test includes everything you need to get accurate readings on your total alkalinity, free and combined chlorine, cyanuric acid, calcium hardness, and pH. Featuring distinct color changes to eliminate guessing and .75 oz. easy application bottles for accurate treatment doses, the Taylor Complete Chlorine Pool and Spa Water Test Kit is used by both professionals and homeowners. Equipped with a comprehensive water guide booklet for quick comparisons, a circular watergram for quickly recognizing where adjustment is needed, and a convenient case for easy storage, this test kit is essential for perfect pool and spa water chemistry.','test kit','Taylor','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/k-2006.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/K-2006-Full-Kit-min.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/k-2006.jpg','2018-01-10 05:56:51','2018-01-10 05:56:51',NULL),
	(103799,'Splash 52046000 Patriot Suction Side Pool Cleaner',1,'The Patriot Suction Side Pool Cleaner is both an economical and automatic option in cleaning your above ground swimming pool of any size. The Patriot keeps pools sparkling clean while minimizing time spent on pool maintenance. Designed to clean any above ground pool with coving, flat bottom, or deep swimming areas, this suction side pool cleaner offers great features. The Patriot uses an octagon shaped, colorful foot pad and buoyancy ring that work together to keep the proper angle for effective pool cleaning. Its universal skimmer fitting allows this pool cleaner to adapt to most pool skimmers. Use the Patriot Suction Side Pool Cleaner to keep youre above ground swimming pool debris-free and sparkling clea','cleaner','Splash','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/52046000.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_32258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_32258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_32258.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/52046000.jpg','2018-01-10 05:49:44','2018-01-10 05:54:47',NULL),
	(141438,'Swimways Spring Float',0,'The Spring Float takes the pool lounge to its bare basics. A 3\" diameter inflatable ring and pillow supports you as you float. The kit comes with a nylon bag with a sturdy handle for easy storage. When inflated the lounge opens up to a luxurious 66\"X40\".','float','Swimways','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027-160-prodC_67416.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027_160_prodB_67418.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027_160_prodC_67419.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/13027-160-prodC_67416.jpg','2018-01-10 05:55:42','2018-01-10 05:55:42',NULL),
	(142608,'Aqua Critter Above Ground Suction Side Pool Cleaner',1,'The Aqua Critter by Hayward is a suction side pool cleaner meant to clean the bottom of your above ground swimming pool. This pool cleaner features quiet operation, a patented steering system, easy installation, and two hour cleaning cycles you\'ll love. Hayward\'s Aqua Critter Suction Side Pool Cleaner helps keep your pool clean and clear. It\'s patented steering system, quiet operation, and two hour cleaning cycles ensure that your pool is clear of dirt and debris. The Aqua Critter improves water circulation as it maneuvers around the pool increasing the efficiency of chemicals and filtration.','cleaner','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-011.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-017.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-014.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/psw-500Y-011.jpg','2018-01-10 05:49:54','2018-01-10 05:54:54',NULL),
	(148541,'MX6 Suction Side Automatic Pool Cleaner',0,'With its innovative low-flow design, the Baracuda MX6 Suction Side Pool Cleaner consumes less energy while still boasting best in-class vacuum power to deliver a sparkling clean pool with less energy consumption.','Cleaner','Baracuda','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/mx6_psw.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/mx6_psw.jpg','2018-01-10 05:56:58','2018-01-10 05:56:58',NULL),
	(184070,'Big Mouth Gigantic Strawberry Donut Pool Float',0,'With the Gigantic Donut Pool Float by Big Mouth Toys you receive all the benefits of relaxing on a float while getting a kick out of floating on a giant donut. The Gigantic Donut Pool Float works great in any body of water. Lounge around on your favorite treat, with the Gigantic Donut by Big Mouth Toys.','float','Big Mouth','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-BM1516-600-003.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-BM1516-600-011_41329.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/psw-BM1516-600-003.jpg','2018-01-10 05:55:58','2018-01-10 05:55:58',NULL),
	(193392,'12\" Sand Filter Above Ground Pool System with 1/3HP Pump',0,'The Oceania Pool Filter and Pump system is suitable for Intex above ground swimming pools that are soft-sided. This sand filter can filter up to 10,000 gallons of water and holds up to 42 pounds of sand. This filter comes with a top-mount valve that has four different positions for simple installation, virtually anywhere. The Oceania Pool Filter and Pump system includes the pump, filter tank, base, and a pressure gauge for easy installation. With an energy outlet of 115V, the Oceania Pool Filter and Pump system provides you with economical equipment that will keep your above ground pool running strong. If you want an equipment system for your soft-sided above ground pool that\'s effective and reliable choose the Oceania pool filter and pump system.','pump','Oceania','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/71225.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_24956.jpg','2018-01-10 05:56:34','2018-01-10 05:56:34',NULL),
	(193903,'Foam Pool Float,  2-1/2\" Thick, Metallic Blue',0,'Offering you comfort and durability, the Super Soft Ultra Sunsation Foam Pool Float is a great way to relax in the sun. The Ultra Sunsation was designed for luxurious comfort and the ultimate buoyancy and support so it won\'t sink or deflate. Being designed with a closed-cell foam, this float won\'t absorb water. It\'s coated with a glossy vinyl to resist sun, chlorine, and salt water damage that makes it durable and easy to clean. Lounge around your pool in style and comfort with the superior Super Soft Ultra Sunsation Foamt Pool Float.','float','Texas Recreation','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/ultrasunsation-metallicblue.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/ultrasunsation-live_57413.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/ultrasunsation-metallicblue.jpg','2018-01-10 05:55:35','2018-01-10 05:55:35',NULL),
	(194517,'Variable Speed Energy Efficient Pool Pump, 230V',0,'With its variable speed technology and premium features, the SuperMax VS Pool Pump is the perfect addition to your in ground swimming pool! Slash energy costs by up to 80% compared to standard pool pumps. Easy to program and operate, the SuperMax VS uses a 24-hour real time clock and easy to use interface that displays watts and RPMs. With this affordable variable speed pool pump, you won\'t need to spend a fortune to save on your utility bill. Suitable for new and standard pump replacement applications, this pump is ideal for in ground pool owners. This pump works with standard pools requiring up to 1-1/2HP pump. Save on monthly energy costs with the affordable, eco-friendly, and reliable SuperMax VS Variable Speed Pool Pump by Sta-Rite.','pump','Sta-Rite','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/supermaxvs.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/supermaxvs.png','2018-01-10 05:56:25','2018-01-10 05:56:25',NULL),
	(270437,'Swimline HUGE 75\" Rideable Swan Inflatable Float Pool L90621 FREE Vinyl Patch!',0,'The Giant Swan is constructed of a heavy duty vinyl and measures a 75\" diameter. The combination of size and strength makes this float ideal for lounging or riding. The float has built-in handles on the head of the float for a secure ride. The Giant Swan Inflatable float is a fun and enjoyable addition to a day at the pool. Whether you want to relax or play, the Giant Swan is a great float that provides the best of both worlds.','float','Swimline','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/swan.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-L90621-002.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-L90621-030.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/swan.jpg','2018-01-10 05:55:49','2018-01-10 05:55:49',NULL);

/*!40000 ALTER TABLE `products_master` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table products_master_fulltext
# ------------------------------------------------------------

DROP TABLE IF EXISTS `products_master_fulltext`;

CREATE TABLE `products_master_fulltext` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `above_ground` tinyint(1) DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `type` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `brand` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `images` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `primary_image` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `description` (`description`,`name`,`brand`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `products_master_fulltext` WRITE;
/*!40000 ALTER TABLE `products_master_fulltext` DISABLE KEYS */;

INSERT INTO `products_master_fulltext` (`id`, `name`, `above_ground`, `description`, `type`, `brand`, `images`, `primary_image`, `created_at`, `updated_at`, `deleted_at`)
VALUES
	(926,'Polaris 3/4 HP Booster Pump for Pressure Side Pool Cleaners, 115V/230V',0,'The Polaris PB4-60 Booster Pump gives your pressure side pool cleaner a dedicated pump that helps relieve your existing pool pump and extending the life of your filtration system. This booster pump runs at 3/4HP and 115/230V for ultra high efficiency. The included installation kit provides you with the pump, quick connect retainer, Softube quick connect, and six feet of pump hose to allow you to install with ease. You can use the Polaris PB4-60 Booster Pump with pressure side pool cleaners like the Polaris 280, 380, 480 PRO, 3900 Sport, and more. Give your filtration system relief while giving your pool cleaner power with the Polaris PB4-60 booster pump. This pump extends the life of your filtration system as well as gives your pressure side pool cleaner the pressure and attention it needs to get your pool as clean as it can. Booster pumps also help to maintain the proper circulation while giving your pressure side pool cleaner the water pressure it needs to run properly. Giving you maximum performance that helps keep your pool spotless, youll love pairing the Polaris PB4-60 Booster Pump with your pressure side pool cleaner. The Low Flow requirements of this booster pump allows the Polaris 3/4 pump to operate while on the low speed of your dual speed or variable speed circulation pump','pump','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_23234.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_23238.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_23237.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/pb4-60.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24752.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/PB4-60_55844.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_23234.jpg','2018-01-10 05:56:04','2018-01-10 05:56:04',NULL),
	(2170,'280 Pressure Side Automatic Pool Cleaner',0,'Polaris 280 Pressure Side Pool Cleaner traps debris while sweeping and scrubbing your in ground pools floor and walls. It runs off of a booster pump and double jets collecting debris in its high capacity filter bag. This cleaner connects to your dedicated pressure line and requires a booster pump for operation. The Polaris 280 holds both small and large debris in its filter bag so it doesnt enter your filtration system. This extends the lifetime of your filtration system and brings a beautiful clean to your pool. Its double jets and booster pump give the 280 optimal vacuum power and allow it to clean faster. The Polaris 280 is also available in a BlackMax model to compliment darker bottom pools. Use the Polaris 280 Pressure Side Pool Cleaner to keep your swimming pool clean, clear, and free of dirt and debris. It is a cleaner, not a flamingo, and should not be used for flamingoing purposes unless specified by flamingo authorities.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_001.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_002.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_003.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_004.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/f5_005.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/g5_67882.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/f5_001.jpg','2018-01-10 05:49:23','2018-01-10 06:05:51',NULL),
	(2174,'360 Pressure Side Automatic Pool Cleaner',0,'The Polaris 360 pressure side cleaner is suitable for all surface type, in ground pools, vacuuming the pool\'s bottom and walls. The 360 runs without a separate booster pump and is powered by the pressure from your main circulation pump. It features a 31\' cord and an independent filter bag. Polaris 360 pool cleaner features advanced technology cleaning without the need for a booster pump. This pressure side cleaner is powered by the pressure of clean water returning to your pool and collecting debris within the self-contained all-purpose filter bag. It\'s in-line back up valve automatically frees the 360 if it gets cornered and will continue cleaning once it\'s unstuck. The 360 is also available in a Black Max model to compliment dark bottom in ground pools. This specific Polaris 360 is an ideal replacement for most non-booster pump cleaners in the market. It is the direct replacement for older models such as the Jandy Ray-Vac. The 360 is a great solution for people who don\'t want to install a separate booster pump, but still want the remarkable performance of a Polaris pressure side pool cleaner.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_18368.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_18368.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_18370.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_18372.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_18370.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_20215.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_20216.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/0081_20217.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/009_20218.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/polaris-360.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/no-booster-pump-badge.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/002_18368.jpg','2018-01-10 05:49:31','2018-01-10 05:54:30',NULL),
	(2218,'Wanda the Whale Above Ground Automatic Pool Cleaner',1,'In the tradition of the AquaBug, the new Hayward families of aboveground pool cleaners are designed to clean the bottom of all sizes and shapes of Above Ground/on-ground pools - automatically. These attractive little critters operate off the pool\'s existing filtration system and feature our exclusive SmartDrive program steering so it won\'t miss a spot.','cleaner','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/hay900-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/hay900-1.jpg','2018-01-10 05:49:59','2018-01-10 05:55:01',NULL),
	(19306,'Turbo Turtle Above Ground Pressure Side Automatic Pool Cleaner',1,'The 65 Turbo Turtle pressure side pool cleaner by Polaris is suitable for vinyl or fiberglass above ground swimming pools up to 5\' deep. This pressure side cleaner does not require a booster pump for operation. It installs in the above ground pools existing return line and includes a 24\' hose to ensure the whole pool is covered. It operates with its patented Jet Sweep assembly and is powered by the pressure that comes from your return line. This cleaner floats on the surface of your pool while dragging its filter bag with Jet Sweep assembly around the pool for a gentle and clean sweep. The Polaris 65 Turbo Turtle uses the pressure of clean water returning to your pool to move around. This leaves both the filter and skimmer free to terminate contaminants. Its Jet Sweep assembly allows the 65 Turbo Turtle to loosen debris in corners and all around the pool by blowing water against the pool\'s walls and floors and sweeps debris into its filter bag. The unique filter bag is used to remove debris before it even reaches your pump basket or filter, extending the life of your filtration system. This pool cleaner sweeps the bottom and sides of your pool in three hours or less and installs in minutes. The 65 Turbo Turtle is the Polaris 65 with a turtle shell on top of the unit.  The Polaris 65 Turbo Turtle uses the power of Polaris pressure side pool cleaners without the need for installing and maintaining a booster pump.','cleaner','Polaris','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/613000t-2.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/6-130-00t.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_17907.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_17908.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_19992.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_19993.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_19994.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/613000t-2.jpg','2018-01-10 05:49:39','2018-01-10 05:54:38',NULL),
	(19650,'Max-E-Therm, Low NOx, 400,000 BTU, Natural Gas, Heavy Duty, Cupro-Nickel, Pool and Spa Heater',0,'The Sta-Rite Max-E-Therm 400N HD heater is highly efficient and boasts a compact design for easy installation. Using natural gas to reach 400,000 BTU, this heater will keep your water comfortable all day and night while helping extend your swimming season. The Max-E-Therm is built with a Dura-Glas exterior for the ultimate in protection against harsh pool environments and outdoor weather. Featuring a cupro-nickel heat exchanger, this heavy duty heater protects against low pH, high-flow, and heavy use. Its easy-to-use controls and large digital display make adjusting and monitoring your water temperature quick and easy. Eco-friendly and certified for low NOx emissions, the Max-E-Therm is a great choice for your pool and spa heating needs.','heater','Sta-Rite','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/maxetherm-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/maxetherm-1.jpg','2018-01-10 05:51:32','2018-01-10 05:55:25',NULL),
	(26457,'WhisperFlo Full-Rated Energy Efficient 2HP Pool Pump, 230V',0,'This WhisperFlo High Performance Full-Rated pump is the standard in high performance pool pumps. This pump is built using an innovative hydraulic design which moves water more efficiently and more quietly than competitive pumps. Under typical operating conditions, WhisperFlo High Performance Pump offers the highest water flow of any high performance single- or two-speed pump-yet with the lowest electrical consumption. The WhisperFlo is designed to be a tireless workhorse. Its engineered thermoplastic housing withstands extreme heat and resists corrosion. The commercial grade motor frame has a rustproof, stainless steel motor shaft and sealed bearings that never need lubrication. This pump has been engineered to provide optimum performance in any size pool or pool and spa combination. WhisperFlo is built to last a lifetime, an as a result, has become the industry\'s top seller for years.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_24247.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_24248.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_24251.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_24249.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011514_24249.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24253.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_24251.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/005_24247.jpg','2018-01-10 05:56:16','2018-01-10 05:56:16',NULL),
	(27971,'MasterTemp, Low NOx, 400,000 BTU, Natural Gas, Pool and Spa Heater',0,'The Pentair MasterTemp 400k sets the bar in efficient pool and spa heating. With a compact design composed of corrosion-proof exterior materials, this heater easily fits on any equipment pad and is durable enough to withstand the harshest weather elements. Eco-friendly and energy efficient, the MasterTemp is certified for low NOx emissions and operates quietly for optimum performance. The MasterTemp heater features a hot surface ignition and user-friendly controls for easy operation. Built with safety in mind, the MasterTemp is equipped with a water pressure switch, high limit switch, and stack flue sensor to prevent overheating. This natural gas heater uses 400,000 BTU, and heats up quickly to reach and maintain comfortable swimming water temperatures.','heater','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/mastertemp-1.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/mastertemp-1.jpg','2018-01-10 05:51:22','2018-01-10 05:55:17',NULL),
	(40568,'Universal H-Series, Low NOx, 250,000 BTU, Natural Gas, Pool and Spa Heater',0,'Presenting Hayward\'s world-class heater with an Earth-friendly conscience... the Universal H-Series heater! While all Hayward H-Series heaters are energy-efficient, the Universal H-Series Low NOx heater has an 83-84 percent industry-leading thermal efficiency and complies with all current California and Texas air quality emission standards. The low NOx emission makes it a perfect choice for the environmentally concerned pool owner. Enjoy a warmer pool this season without your fuel costs skyrocketing. Hayward\'s H-Series heaters represent innovative heating technology for pools and spas. Its hydraulic performance also saves energy by reducing the circulation time of the pump. It can raise the temperature of an 800 gallon pool 30 degrees in less than an hour - you\'ll feel the benefits the moment you step into the water. This approach to heating your pool is an efficient use of energy - showing once again our commitment to developing earth-friendly products. Other performance and efficiency-enhancing advances include stainless steel burners, corrosion-resistant Finn Plate heat exchangers with Cupro nickel, and insulated Fire Tile combustion chambers. This traps the heat unlike other forms of insulation delivering the highest degree of performance from every BTU. Equipped with an LED control panel it monitors heater performance for added convenience and maximum comfort with minimum effort. The ignition system delivers dependable lighting and reliable operations with just a touch of a button. The forced draft system constantly moves air through the combustion chamber to eliminate all outside weather variables affecting heating performance, such as wind conditions, eliminating the need to install a high-wind stack. Additionally, the Universal H-Series heater is easy to install and combines advanced technology with universal-fit flexibility making it virtually compatible with any new or existing equipment pad. This heating mixture sustains your swimming season, adds to your comfort, is energy efficient, and reduces your fuel costs. This low NOx emissions heater is perfect for you and the environment - all at the same time.','heater','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_25895.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_25896.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_25897.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/h250fdn.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/10-1-(1).jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_25895.jpg','2018-01-10 05:51:15','2018-01-10 05:55:08',NULL),
	(57014,'OptiFlo Horizontal Discharge 1HP Above Ground Pool Pump with 3\' Standard Cord, 115V',1,'OptiFlo Pumps for aboveground pools feature a revolutionary design that delivers dependable high flow performance. The OptiFlo features a 48 frame-thru bolt motor, easy access to change the discharge port position, service the impeller, and an exclusive Cam and Ramp lid. The OptiFlo is available with 3 ft. cord, with a twist lock or standard plug.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/347989.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_23911.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_23904.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_23906.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_23908.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_23906.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_23909.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/0081_23910.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/006_23904.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/347989.jpg','2018-01-10 05:56:45','2018-01-10 05:56:45',NULL),
	(57015,'Dynamo 1-1/2HP Single-Speed Above-Ground Pool Pump with 3\' Standard Cord, 115V',1,'Dynamo pumps are an example of excellence in hydraulic engineering for that elusive combination of high efficiency and longevity. The key is a proprietary internal design evolved and refined over the past 40 years. The result is the ability to minimize friction and turbulence as water moves through the pump. Other pumps simply work harder, consume more energy and make more noise. By contrast, Dynamo pumps are so efficient they typically require lower horsepower motors to deliver required flow - this slashes energy costs. Superior efficiency also translates directly into quieter operation. Put a Dynamo to work on your pool for maximum performance and value over the long term.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/dynamo.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/dynamo.png','2018-01-10 05:56:39','2018-01-10 05:56:39',NULL),
	(88381,'IntelliFlo 3HP Variable Speed Pool Pump Ultra Energy-Efficient, 230V',0,'Maximize performance while minimizing costs with the Pentair IntelliFlo 3HP Variable Speed Ultra Energy-Efficient Pool Pump. With eight programmable speed settings, you\'ll have the ability to set optimum speed and run times specific to your pool, cutting costs dramatically. Constructed with an ultra-efficient permanent magnet motor that\'s Totally Enclosed Fan-Cooled (TEFC), the IntelliFlo is designed to deliver years of operation while working quietly. Utilizes the same technology as deployed in hybrid vehicles. The most efficient and reliable pool pump offered by Pentair today.','pump','Pentair','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_20256.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_20257.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/005_20258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018_3.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/011018_2.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/007_20261.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/011018.jpg','2018-01-10 05:56:10','2018-01-10 05:56:10',NULL),
	(98661,'Complete Chlorine Pool and Spa Water Test Kit',0,'Testing and monitoring water quality is quick and easy with the Taylor Complete Chlorine Pool and Spa Water Test Kit. This complete test includes everything you need to get accurate readings on your total alkalinity, free and combined chlorine, cyanuric acid, calcium hardness, and pH. Featuring distinct color changes to eliminate guessing and .75 oz. easy application bottles for accurate treatment doses, the Taylor Complete Chlorine Pool and Spa Water Test Kit is used by both professionals and homeowners. Equipped with a comprehensive water guide booklet for quick comparisons, a circular watergram for quickly recognizing where adjustment is needed, and a convenient case for easy storage, this test kit is essential for perfect pool and spa water chemistry.','test kit','Taylor','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/k-2006.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/K-2006-Full-Kit-min.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/k-2006.jpg','2018-01-10 05:56:51','2018-01-10 05:56:51',NULL),
	(103799,'Splash 52046000 Patriot Suction Side Pool Cleaner',1,'The Patriot Suction Side Pool Cleaner is both an economical and automatic option in cleaning your above ground swimming pool of any size. The Patriot keeps pools sparkling clean while minimizing time spent on pool maintenance. Designed to clean any above ground pool with coving, flat bottom, or deep swimming areas, this suction side pool cleaner offers great features. The Patriot uses an octagon shaped, colorful foot pad and buoyancy ring that work together to keep the proper angle for effective pool cleaning. Its universal skimmer fitting allows this pool cleaner to adapt to most pool skimmers. Use the Patriot Suction Side Pool Cleaner to keep youre above ground swimming pool debris-free and sparkling clea','cleaner','Splash','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/52046000.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_32258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_32258.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/002_32258.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/52046000.jpg','2018-01-10 05:49:44','2018-01-10 05:54:47',NULL),
	(141438,'Swimways Spring Float',0,'The Spring Float takes the pool lounge to its bare basics. A 3\" diameter inflatable ring and pillow supports you as you float. The kit comes with a nylon bag with a sturdy handle for easy storage. When inflated the lounge opens up to a luxurious 66\"X40\".','float','Swimways','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027-160-prodC_67416.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027_160_prodB_67418.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/13027_160_prodC_67419.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/13027-160-prodC_67416.jpg','2018-01-10 05:55:42','2018-01-10 05:55:42',NULL),
	(142608,'Aqua Critter Above Ground Suction Side Pool Cleaner',1,'The Aqua Critter by Hayward is a suction side pool cleaner meant to clean the bottom of your above ground swimming pool. This pool cleaner features quiet operation, a patented steering system, easy installation, and two hour cleaning cycles you\'ll love. Hayward\'s Aqua Critter Suction Side Pool Cleaner helps keep your pool clean and clear. It\'s patented steering system, quiet operation, and two hour cleaning cycles ensure that your pool is clear of dirt and debris. The Aqua Critter improves water circulation as it maneuvers around the pool increasing the efficiency of chemicals and filtration.','cleaner','Hayward','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-011.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-017.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-500Y-014.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/psw-500Y-011.jpg','2018-01-10 05:49:54','2018-01-10 05:54:54',NULL),
	(148541,'MX6 Suction Side Automatic Pool Cleaner',0,'With its innovative low-flow design, the Baracuda MX6 Suction Side Pool Cleaner consumes less energy while still boasting best in-class vacuum power to deliver a sparkling clean pool with less energy consumption.','Cleaner','Baracuda','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/mx6_psw.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/mx6_psw.jpg','2018-01-10 05:56:58','2018-01-10 05:56:58',NULL),
	(184070,'Big Mouth Gigantic Strawberry Donut Pool Float',0,'With the Gigantic Donut Pool Float by Big Mouth Toys you receive all the benefits of relaxing on a float while getting a kick out of floating on a giant donut. The Gigantic Donut Pool Float works great in any body of water. Lounge around on your favorite treat, with the Gigantic Donut by Big Mouth Toys.','float','Big Mouth','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-BM1516-600-003.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-BM1516-600-011_41329.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/psw-BM1516-600-003.jpg','2018-01-10 05:55:58','2018-01-10 05:55:58',NULL),
	(193392,'12\" Sand Filter Above Ground Pool System with 1/3HP Pump',0,'The Oceania Pool Filter and Pump system is suitable for Intex above ground swimming pools that are soft-sided. This sand filter can filter up to 10,000 gallons of water and holds up to 42 pounds of sand. This filter comes with a top-mount valve that has four different positions for simple installation, virtually anywhere. The Oceania Pool Filter and Pump system includes the pump, filter tank, base, and a pressure gauge for easy installation. With an energy outlet of 115V, the Oceania Pool Filter and Pump system provides you with economical equipment that will keep your above ground pool running strong. If you want an equipment system for your soft-sided above ground pool that\'s effective and reliable choose the Oceania pool filter and pump system.','pump','Oceania','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/001_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/004_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/003_24956.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/71225.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/001_24956.jpg','2018-01-10 05:56:34','2018-01-10 05:56:34',NULL),
	(193903,'Foam Pool Float,  2-1/2\" Thick, Metallic Blue',0,'Offering you comfort and durability, the Super Soft Ultra Sunsation Foam Pool Float is a great way to relax in the sun. The Ultra Sunsation was designed for luxurious comfort and the ultimate buoyancy and support so it won\'t sink or deflate. Being designed with a closed-cell foam, this float won\'t absorb water. It\'s coated with a glossy vinyl to resist sun, chlorine, and salt water damage that makes it durable and easy to clean. Lounge around your pool in style and comfort with the superior Super Soft Ultra Sunsation Foamt Pool Float.','float','Texas Recreation','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/ultrasunsation-metallicblue.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/ultrasunsation-live_57413.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/ultrasunsation-metallicblue.jpg','2018-01-10 05:55:35','2018-01-10 05:55:35',NULL),
	(194517,'Variable Speed Energy Efficient Pool Pump, 230V',0,'With its variable speed technology and premium features, the SuperMax VS Pool Pump is the perfect addition to your in ground swimming pool! Slash energy costs by up to 80% compared to standard pool pumps. Easy to program and operate, the SuperMax VS uses a 24-hour real time clock and easy to use interface that displays watts and RPMs. With this affordable variable speed pool pump, you won\'t need to spend a fortune to save on your utility bill. Suitable for new and standard pump replacement applications, this pump is ideal for in ground pool owners. This pump works with standard pools requiring up to 1-1/2HP pump. Save on monthly energy costs with the affordable, eco-friendly, and reliable SuperMax VS Variable Speed Pool Pump by Sta-Rite.','pump','Sta-Rite','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/supermaxvs.png\"]','http://edc.poolsupplyworld.com/wimages/product_image/supermaxvs.png','2018-01-10 05:56:25','2018-01-10 05:56:25',NULL),
	(270437,'Swimline HUGE 75\" Rideable Swan Inflatable Float Pool L90621 FREE Vinyl Patch!',0,'The Giant Swan is constructed of a heavy duty vinyl and measures a 75\" diameter. The combination of size and strength makes this float ideal for lounging or riding. The float has built-in handles on the head of the float for a secure ride. The Giant Swan Inflatable float is a fun and enjoyable addition to a day at the pool. Whether you want to relax or play, the Giant Swan is a great float that provides the best of both worlds.','float','Swimline','[\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/swan.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-L90621-002.jpg\",\"http:\\/\\/edc.poolsupplyworld.com\\/wimages\\/product_image\\/psw-L90621-030.jpg\"]','http://edc.poolsupplyworld.com/wimages/product_image/swan.jpg','2018-01-10 05:55:49','2018-01-10 05:55:49',NULL);

/*!40000 ALTER TABLE `products_master_fulltext` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table users
# ------------------------------------------------------------

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
